name:                spacemonkey
version:             0.1.0.0
github:              "tkuriyama/spacemonkey"
license:             BSD3
author:              Taro Kuriyama
maintainer:          taro@tarokuriyama.com
copyright:           2020 Taro Kuriyama

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/spacemonkey#readme>

dependencies:
  - base >= 4.7 && < 5
  - Spock >=0.11
  - mtl
  - text
  - acid-state
  - safecopy
  
library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings
    - DeriveDataTypeable
    - TemplateHaskell
    - TypeFamilies
  dependencies:
    - elm-bridge
    
executables:
  spacemonkey-make:
    main:                Main.hs
    source-dirs:         make/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - spacemonkey
    - elm-bridge
    
  spacemonkey-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N    
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - spacemonkey

tests:
  spacemonkey-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - spacemonkey
